# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-05 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Screams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screamer', models.CharField(max_length=50)),
                ('scream', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
